# Generated by Django 6.0.1 on 2026-01-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
